= jFocus 2023 Stockholm
Per Minborg
:toc:
:homepage: http://minborgsjavapot.blogspot.com/

== Introduction
In my talk at jFocus 2023 in Stockholm, I talked about project Panama and more specifically about the Foreign Function and Memory API (FFM).

== Clone Me!
All code and the entire presentation can be cloned via https://github.com/minborg/articles

== Live Demos
Here is a list of the live demos made at jFocus:

=== link:src/main/java/org/minborg/jfocus2023/Demo1MemorySegment.java[Demo 1: Memory Segment]

This class shows basic use of a `MemorySegment` which is an abstraction of a contiguous 64-bit memory region providing:

* _Spatial_, _temporal_ and _thread-confinement_ safety
* Bidirectional interoperability with arrays and various `ByteBuffer` types.

=== link:src/main/java/org/minborg/jfocus2023/Demo3MemoryMapping.java[Demo 2: Memory Mapping]

In this demo, we will see how large `MemorySegments` (up to 64 TiB) can be created by means of memory mapping. Read more about memory mapping in http://minborgsjavapot.blogspot.com/2023/01/java-20-colossal-sparse-memory-segments.html[this separate article].


=== link:src/main/java/org/minborg/jfocus2023/Demo2Arena.java[Demo 3: Arena]

This class shows how an `Arena` can be used to provide safe and deterministic release of memory resources.

=== link:src/main/java/org/minborg/jfocus2023/Demo4InfiniteArena.java[Demo 4: Infinite Arena]

This class outlines an implementation of an `Arena` that appears to be able to provide an almost unlimited amount of memory. The concept also allows post-mortem analysis of memory segments used. Read more about the `InfiniteArena` in a separate article http://minborgsjavapot.blogspot.com/2023/01/java-20-almost-infinite-memory-segment.html[here].


=== link:src/main/java/org/minborg/jfocus2023/Demo5MemoryLayout.java[Demo 5: MemoryLayout]

This class shows how the concept of `MemoryLayout` provides a structured way of describing the layout of linear memory. It also shows how memory segments can be dereferenced using `VarHandle` objects that, in turn, can be derived directly from a `MemoryLayout` instance.

=== link:src/main/java/org/minborg/jfocus2023/Demo6Encapsulation.java[Demo 6: Encapsulation]

This class exemplifies how `MemoryLayout` constructs can be encapsulated in normal classes providing "Java-like use" for simplified use with retained performance.

=== link:src/main/java/org/minborg/jfocus2023/Demo7HugeArrays.java[Demo 7: Huge Arrays]

This class shows how large arrays of custom `MemoryLayout` can be constructed. These arrays do not suffer from the normal Java second level of indirection that normal arrays have. These arrays are furthermore not limited to having 2^31^ - ε elements but are instead only limited by the amount of allocated memory.

=== link:src/main/java/org/minborg/jfocus2023/Demo8DownCalls.java[Demo 8: Downcalls]

In this example, we explore how to call native methods using the built-in FFM linker.

=== link:https://github.com/openjdk/jextract/tree/panama/samples/libzstd[Demo 9: Integrating with zstd]

In this demo, we will see how easy it is to integrate with an existing native library and call it directly from Java.


== Interesting Panama Projects and Resources
https://github.com/carldea/panama4newbies/tree/main[Panama 4 Newbies]


== Safe Harbor Statement
The following is intended to outline our general product direction. It is intended
for information purposes only, and may not be incorporated into any contract. It is not a commitment to deliver any material, code, or functionality, and should not be relied upon in making purchasing decisions. The development, release, timing, and pricing of any features or functionality described for Oracle’s products may change and remains at the sole discretion of Oracle Corporation.

link:../../LICENSE[Copyright (c) 2023, Oracle and/or its affiliates.]