= Value Mapping with the FFM Record Mapper
Doc Writer <per dash ake dot minborg at oracle dot com>
:toc:

== Background
FFM Mappers provide mapping from raw memory in the form of a `MemorySegment` to a Java object and are envisioned in two flavours:

* Record Mappers
* Interface Mappers

=== Record Mappers
A _Record Mapper_ can unmarshal (deserialize) a `java.lang.Record` from a `MemorySegment` and can also marshal (serialize) a record instance into a `MemorySegment". It does not hold any reference to the segment.

=== Interface Mappers
An _Interface Mapper_ acts like a wrapper around a `MemorySegment` and provide normal Java bean-like semantics (e.g. getters and setters) to allow access to individual elements. While a similar mechanism can be achieved by deriving `VarHandles` using the current FFM API, interface wrappers provide much better abstraction and enable easier-to-read code.

An outline of the main requirements for FFM Mappers can be found link:README.adoc[here]

== Value Mapping
Eventually, groups and/or sequences layouts will have values in their outermost leafs. The question then arises how these leaves can be matched and mapped with respect to types.

=== Value Mapping Background

One of the https://github.com/minborg/panama-foreign/blob/555a15addad12e41f71f25d567661cc27efde4a2/src/java.base/share/classes/java/lang/foreign/GroupLayout.java#L112[prototypes of a record mapper], requires the type of each record component element to be *exactly* matched with the type of the corresponding element in a `GroupLayout`. For example, a record class like this:

[source, java]
----
public record Point(int x, int y){}
----

can be used to create a record mapper using this layout:

[source, java]
----
var layout = MemoryLayout.structLayout(JAVA_INT.withName("x"), JAVA_INT.withName("y"));
----

But not using this other layout:

[source, java]
----
var layoutByte = MemoryLayout.structLayout(JAVA_BYTE.withName("x"), JAVA_BYTE.withName("y"));
----

As can be seen, the names of the record component and the name of the corresponding layout must equal each other in order to be matched.

Also, the types are identical for matched components and elements.

While this definition is clear and easy to understand, it will present a problem when mapping types that have different physical representation on different platforms (e.g. a C `long` on Windows is 32 bits while it is 64 bits on Linux).

It is also an unnecessary restriction in many other cases. Imagine, for example, that one would have a record with x and y-coordinated declared as `long` but might come across `MemorySegment` with different representations of the coordinates (e.g. `short`, `int` or `long`). Relaxing conversion restrains would allow the record with `long` coordinates to reflect all such `MemorySegment` variants.

Hence, it would be desirable to allow more flexibility in terms of value mapping

=== Reversibility

In some applications, it is envisioned that mapping will only be performed in one direction (e.g. a native method returns a struct that we are interested in examining). In others, mapping needs to be performed in both directions (e.g. a native library handles graphics where shapes can be drawn and operated on (e.g. point.translate() -> Point)).

For two-way mappers, it is important to decide if a record mapper should be viewed as reversible in the sense that any pair of marshall/unmarshall operation combined is an identity operation. In other words, if a record `A` is written to memory and then read back as another instance `B`, then `A` must equal `B` for all defined values of `A`. If so, this imposes restrictions on the potential lossless conversions available.

=== Widening & Narrowing

A relate issue is if we should allow widening & narrowing. One principle could be that only conversions that is statically _always_ lossless are allowed (e.g. widening an `int` to a `long`) or if a conversion that dynamically _happens_ to be lossless is allowed (e.g. narrowing a `long` in the interval [Integer.MIN_VALUE, Integer.MAX_VALUE] to an `int`) akin to https://openjdk.org/jeps/455[JEP 455: Primitive types in Patterns, instanceof, and switch (Preview)].

== Explicit conversion
It is possible to allow custom conversion (defined by the user) much like the more https://orahub.oci.oraclecorp.com/raffaello.giulietti/record-mapper/-/blob/master/src/playground/RecordMapper.java#L287[general record mapper] demonstrated by Raffaelo (internal link). This would move the responsibility from the library to the user and would make it much easier to specify.


== Configuring Mappers
One solution would be to start of with a default configuration where names are matched and where the types would have to be identical but then provide a builder-type configuration phase where the mapping requisites could be specified in detail. Configuration could entail:

[cols="1,1,1, 1"]
|===
|Property |Default Value |Conf Method |Comment

|`Lookup`
|`MethodHandles.publicLookup()`
|`withLookup(Lookup lookup)`
| Providing a custom lookup allows internal classes to be used.

|_matching types_
|_types_ identical
|withWidening()
|Unlocks *Widening Primitive Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.2[§5.1.2]

|_matching types_
|_types_ identical
|withNarrowing()
|Unlocks *Narrowing Primitive Conversion* as per https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.3[JLS §5.1.3]

|_matching types_
|_types_ identical
|withBoxing()
|Unlocks *Boxing Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.7[§5.1.7]

|_matching types_
|_types_ identical
|withUnboxing()
|Unlocks *Unboxing Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.8[§5.1.8]

|_matching types_
|_types_ identical
|withStringConversion()
|Unlocks *String Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.11[§5.1.11]

|_matching types_
|_types_ identical
|withAllConversions()
|Unlocks *all* the conversions above. This is equivalent to: `.withWidening()
.withNarrowing()
.withBoxing()
.withUnboxing()
.withStringConversion()`

|_matching types_
|_types_ identical
|withExactNarrowing()
|Unlocks *Narrowing Primitive Conversion* as per https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.3[JLS §5.1.3] but
throws a runtime exception if an attempt is made to convert a `long`, `int` or `short` to an `int`, `short` or `byte` and a loss of
information would be the result. See `Math.toIntExact`. Always throws a runtime exception if an attempt is made to convert a `float` or a `double` to any other primitive representation.

|_matching_
|_names_ equals and _types_ identical
|There `matching(SequencedCollection<PathElement> source, MethodReference<T, R> recordTarget, Function<?, ? extends R, ?> mapper)`
or `matching(SequencedCollection<PathElement> elements, MethodReference<T, R> recordMethod, MethodHandle mapper)` and in the opposite direction `matching(MethodReference<T, R> recordTarget, SequencedCollection<PathElement> source, Function<? super R, ?> mapper)` or `matching(MethodReference<T, R> recordMethod, SequencedCollection<PathElement> elements, MethodHandle mapper)`
| These methods allow custom mapping of any record fields of arbitrary depth to any value layout in a memory layout regardless of names and types.

|===

Note:: The `MethodReference<T, R>` is a _new_ function that is able to return the `java.lang.reflect.Method` referenced. `MethodReference` is also composable such that it is possible to describe constructs of arbitrary depth `MethodReference.of(Line::begin).andThen(Point::x)`. This is related to project Babylon.

== References

 [1]. "Prototype of a Record Mapper", Minborg et al., https://github.com/minborg/panama-foreign/blob/555a15addad12e41f71f25d567661cc27efde4a2/src/java.base/share/classes/java/lang/foreign/GroupLayout.java#L112

 [2]. "JEP 455: Primitive types in Patterns, instanceof, and switch (Preview)", Bimpoudis et al., https://openjdk.org/jeps/455

 [3]. "Record Mapper Prototype", Giulietti, https://orahub.oci.oraclecorp.com/raffaello.giulietti/record-mapper/-/blob/master/src/playground/RecordMapper.java#L287 (internal)