= Value Mapping with the FFM Record Mapper
Doc Writer <per dash ake dot minborg at oracle dot com>
:toc:

== Background
FFM Mappers provide mapping from raw memory in the form of a `MemorySegment` to a Java object and are envisioned in two flavours:

* Record Mappers
* Interface Mappers

=== Record Mappers
A _Record Mapper_ can unmarshal (deserialize) a `java.lang.Record` from a `MemorySegment` and can also marshal (serialize) a record instance into a `MemorySegment". It does not hold any reference to the segment.

=== Interface Mappers
An _Interface Mapper_ acts like a wrapper around a `MemorySegment` and provide normal Java bean-like semantics (e.g. getters and setters) to allow access to individual elements. While a similar mechanism can be achieved by deriving `VarHandles` using the current FFM API, interface wrappers provide much better abstraction and enable easier-to-read code.

An outline of the main requirements for FFM Mappers can be found link:README.adoc[here]

== Value Mapping
Eventually, groups and/or sequences layouts will have values in their outermost leafs. The question then arises how these leaves can be matched and mapped with respect to types.

=== Value Mapping Background

One of the https://github.com/minborg/panama-foreign/blob/555a15addad12e41f71f25d567661cc27efde4a2/src/java.base/share/classes/java/lang/foreign/GroupLayout.java#L112[prototypes of an FFM record mapper], requires the type of each record component element to be *exactly* matched with the type of the corresponding element in a `GroupLayout`. For example, a record class like this:

[source, java]
----
public record Point(int x, int y) {}
----

can be used to create a record mapper using this layout:

[source, java]
----
var layout = MemoryLayout.structLayout(JAVA_INT.withName("x"), JAVA_INT.withName("y"));
----

but not using this other layout:

[source, java]
----
var layoutLong = MemoryLayout.structLayout(JAVA_LONG.withName("x"), JAVA_LONG.withName("y"));
----

As can be seen, the names of the record component and the name of the corresponding layout must equal each other in order to be matched.

Also, the types are identical for matched components and elements.

While this definition is clear and easy to understand, it will present a problem when mapping types that have different physical representation on different platforms (e.g. a C `long` on Windows is 32 bits while it is 64 bits on Linux).

It is also an unnecessary restriction in many other cases. Imagine, for example, that one would have a record with x and y-coordinated declared as `long` but might come across `MemorySegment` with different representations of the coordinates (e.g. `short`, `int` or `long`). Relaxing conversion restrains would allow the record with `long` coordinates to reflect all such `MemorySegment` variants.

Hence, it would be desirable to allow more flexibility in terms of value mapping

=== Reversibility

In some applications, it is envisioned that mapping will only be performed in one direction (e.g. a native method returns a struct that we are interested in examining). In others, mapping needs to be performed in both directions (e.g. a native library handles graphics where shapes can be drawn and operated on (e.g. point.translate() -> Point)).

For two-way mappers, it is important to decide if a record mapper should be viewed as reversible in the sense that any pair of marshall/unmarshall operation combined is an identity operation. In other words, if a record `A` is written to memory and then read back as another instance `B`, then `A` must equal `B` for all defined values of `A`. If so, this imposes restrictions on the potential lossless conversions available.

=== Widening & Narrowing

A relate issue is if we should allow widening & narrowing. One principle could be that only conversions that is statically _always_ lossless are allowed (e.g. widening an `int` to a `long`). Another principle could be if a conversion that dynamically _happens_ to be lossless is allowed (e.g. narrowing a `long` in the interval [Integer.MIN_VALUE, Integer.MAX_VALUE] to an `int`) akin to https://openjdk.org/jeps/455[JEP 455: Primitive types in Patterns, instanceof, and switch (Preview)].

== Explicit conversion
It is possible to allow custom conversion (defined by the user) much like the more https://orahub.oci.oraclecorp.com/raffaello.giulietti/record-mapper/-/blob/master/src/playground/RecordMapper.java#L287[general record mapper] demonstrated by Raffaelo (internal link). This would shift the responsibility from the library to the user and would make it much easier to specify.


== Configuring Mappers
One solution would be to start of with a default configuration where names are matched and where the types would have to be identical but then provide a builder-type configuration phase where the mapping requisites could be specified in detail. Other configuration items (e.g. Lookup) could also be added this way. Here is an example of how a builder for a mapper might look like:

[cols="1,1,1, 1"]
|===
|Property |Default Value |Conf Method |Comment

|`Lookup`
|`MethodHandles.publicLookup()`
|`withLookup(Lookup lookup)`
| Providing a custom lookup allows internal classes to be used.

|_matching types_
|_types_ identical
|withWidening()
|Unlocks *Widening Primitive Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.2[§5.1.2]

|_matching types_
|_types_ identical
|withNarrowing()
|Unlocks *Narrowing Primitive Conversion* as per https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.3[JLS §5.1.3]

|_matching types_
|_types_ identical
|withBoxing()
|Unlocks *Boxing Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.7[§5.1.7]

|_matching types_
|_types_ identical
|withUnboxing()
|Unlocks *Unboxing Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.8[§5.1.8]

|_matching types_
|_types_ identical
|withStringConversion()
|Unlocks *String Conversion* as per JLS https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.11[§5.1.11]

|_matching types_
|_types_ identical
|withAllConversions()
|Unlocks *all* the conversions above. This is equivalent to: `.withWidening()
.withNarrowing()
.withBoxing()
.withUnboxing()
.withStringConversion()`

|_matching types_
|_types_ identical
|withExactNarrowing()
|Unlocks *Narrowing Primitive Conversion* as per https://docs.oracle.com/javase/specs/jls/se21/html/jls-5.html#jls-5.1.3[JLS §5.1.3] but
throws a runtime exception if an attempt is made to convert a `long`, `int` or `short` to an `int`, `short` or `byte` and a loss of
information would be the result. See `Math.toIntExact`. Always throws a runtime exception if an attempt is made to convert a `float` or a `double` to any other primitive representation.

|_matching types_
|_types_ identical
|There `<S, R> Builder<T> mapping(Class<S> sourceType, Class<R> targetType, Function<? super S, ? extends R> mapper)`
or `<S, R> Builder<T> mapping(Class<S> sourceType, Class<R> targetType, MethodHandle mapper)`
| These methods allow custom mapping between _all_ values of the specified types.

|_matching names_
|_types_ identical
|There `<R> Builder<T> matching(MethodReference<T, R> recordComponent, MemoryLayout.PathElement valueLayout)`
| There might be overloads for matching operations of depth one (with just a single `PathElement`)

|_matching names and types_
|_names_ equals and _types_ identical
|There `<R> Builder<T> mapping(MethodReference<T, R> recordComponentSource, SequencedCollection<MemoryLayout.PathElement> valueLayoutTarget, Function<? super T, ? extends R> mapper)`
or `<R> Builder<T> mapping(MethodReference<T, R> recordComponentSource,
SequencedCollection<MemoryLayout.PathElement> valueLayoutTarget,
MethodHandle mapper)` and in the opposite direction `<R> Builder<T> mapping(SequencedCollection<MemoryLayout.PathElement> valueLayoutSource, MethodReference<T, R> recordComponentTarget, Function<?, ? extends R> mapper)` or `<R> Builder<T> mapping(SequencedCollection<MemoryLayout.PathElement> valueLayoutSource, MethodReference<T, R> recordComponentTarget, MethodReference mapper)`
| These methods allow custom mapping of any record components of arbitrary depth to any value layout in a memory layout regardless of names and types. There might be overloads for matching operations of depth one (with just a single `PathElement`)

|===

Note:: The `MethodReference<T, R>` is a _new_ function that is able to return the `java.lang.reflect.Method` referenced. `MethodReference` is also composable such that it is possible to describe constructs of arbitrary depth `MethodReference.of(Line::begin).andThen(Point::x)`. This is related to project Babylon.

Here is an example of how such a builder could be used to map components of a Point record with `int` components but where the memory segment contains `long` values:

[source,java]
----
public record Point(int x, int y) {}
var layoutLong = MemoryLayout.structLayout(JAVA_LONG.withName("x"), JAVA_LONG.withName("y"));

var mapper = Mapper.Builder.ofRecord(Point.class, layoutLong)
  .withExactNarrowing()
  .toMapper();

var segment = MemorySegment.ofArray(new long[]{3, 4, 1L << 40, 2L << 40});

var point = mapper.get(segment);      // Point[x=3, y=4];
var point2 = mapper.get(segment, 16); // ArithmeticException

mapper.set(segment, new Point(0, 0));

----

Here is another example of how the builder could be used to map components of a `Point` record with `BigInteger` components (rather than `long`):

[source,java]
----
import java.math.BigInteger;
public record Point(BigInteger x, BigInteger y) {}
var layoutLong = MemoryLayout.structLayout(JAVA_LONG.withName("x"), JAVA_LONG.withName("y"));

var unmarshaller = Mapper.Builder.ofRecord(Point.class, layoutLong)
  .mapping(long.class, BigInteger.class, BigInteger::valueOf)
  .toUnmarshaller();

var segment = MemorySegment.ofArray(new long[]{3, 4, 1L << 40, 2L << 40});

var point = unmarshaller.get(segment);      // Point[x=3, y=4];
var point2 = unmarshaller.get(segment, 16); // Point[x=1099511627776, y=1099511627776];

----

Here is yet another example, similar to the previous but where the names are also remapped:

[source,java]
----
import java.math.BigInteger;
public record Point(BigInteger xCoordinate, BigInteger yCoordinate) {}
var layoutLong = MemoryLayout.structLayout(JAVA_LONG.withName("x"), JAVA_LONG.withName("y"));

var unmarshaller = Mapper.Builder.ofRecord(Point.class, layoutLong)
  .mapping(Point::xCoordinate, PathElement.groupElement("x"), BigInteger::valueOf)
  .mapping(Point::yCoordinate, PathElement.groupElement("y"), BigInteger::valueOf)
  .toUnmarshaller();

var segment = MemorySegment.ofArray(new long[]{3, 4, 1L << 40, 2L << 40});

var point = unmarshaller.get(segment);      // Point[x=3, y=4];
var point2 = unmarshaller.get(segment, 16); // Point[x=1099511627776, y=1099511627776];

----

== Builder Prototype

Here is a prototype of the builder exemplified above:

[source,java]
----
    interface Builder<T extends Record> {

        Builder<T> withLookup(MethodHandles.Lookup lookup);

        Builder<T> withWidening();

        Builder<T> withNarrowing();

        Builder<T> withBoxing();

        Builder<T> withUnboxing();

        Builder<T> withStringConversion();

        Builder<T> withAllConversions();

        Builder<T> withExactNarrowing();

        // General type mapping
        <S, R> Builder<T> mapping(Class<S> sourceType, Class<R> targetType, Function<? super S, ? extends R> mapper);

        <S, R> Builder<T> mapping(Class<S> sourceType, Class<R> targetType, MethodHandle mapper);

        // Name mapping
        <R> Builder<T> matching(MethodReference<T, R> recordComponent, MemoryLayout.PathElement valueLayout);

        <R> Builder<T> matching(MethodReference<T, R> recordComponent, SequencedCollection<MemoryLayout.PathElement> valueLayout);

        // Custom name and type mapping (`MethodHandle` overloads not shown for brevity)
        <R> Builder<T> mapping(MethodReference<T, R> recordComponentSource,
                               MemoryLayout.PathElement valueLayoutTarget,
                               Function<? super T, ? extends R> mapper);

        <R> Builder<T> mapping(MethodReference<T, R> recordComponentSource,
                               SequencedCollection<MemoryLayout.PathElement> valueLayoutTarget,
                               Function<? super T, ? extends R> mapper);

        <S, R> Builder<T> mapping(MemoryLayout.PathElement valueLayoutSource,
                                  MethodReference<T, R> recordComponentTarget,
                                  Function<?, ? extends R> mapper);

        <S, R> Builder<T> mapping(SequencedCollection<MemoryLayout.PathElement> valueLayoutSource,
                                  MethodReference<T, R> recordComponentTarget,
                                  Function<?, ? extends R> mapper);


        // Get and set operations in a MemorySegment
        RecordMapper<T> toMapper();

        // Should also provide a long offset coordinate
        Function<MemorySegment, T> toUnmarshaller();

        // Should also provide a long offset coordinate
        BiConsumer<MemorySegment, T> toMarshaller();


        static <T extends Record> Builder<T> ofRecord(Class<T> type, GroupLayout layout) {
            Objects.requireNonNull(type);
            if (Record.class.equals(type)) {
                throw new IllegalArgumentException();
            }
            Objects.requireNonNull(layout);
            return new BuilderImpl<T>(type, layout) {
            };
        }
    }
----

== References

 [1]. "Prototype of a Record Mapper", Minborg et al., https://github.com/minborg/panama-foreign/blob/555a15addad12e41f71f25d567661cc27efde4a2/src/java.base/share/classes/java/lang/foreign/GroupLayout.java#L112

 [2]. "JEP 455: Primitive types in Patterns, instanceof, and switch (Preview)", Bimpoudis et al., https://openjdk.org/jeps/455

 [3]. "Record Mapper Prototype", Giulietti, https://orahub.oci.oraclecorp.com/raffaello.giulietti/record-mapper/-/blob/master/src/playground/RecordMapper.java#L287 (internal)